### PR TITLE
add testthat structure

### PR DESCRIPTION
**Pull request by selimrbd**

### CODE REVIEW

**Comment by selimrbd** [comment]
* adds unit tests
* in dt2vw, allow the target to be NULL (for testing only)
* adds data.table package scope for copy() and setDT() at the beginning of dt2vw

**Comment by eddelbuettel** [comment]
You own that then ... because I am more of a RUnit user :)

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
@SelimRaboudi Apologies for taking soooo long to get back to this.  I just looked at this yesterday, and the test plain fails.  My `/usr/bin/vw` (Ubuntu 17.05, distro-version of `vw`) does not throw the exception.

Does this work for you?

**Comment by eddelbuettel** [comment]
Weird. Looked at it again a day later, and now it does what it is supposed to do. (Also, of course, does not use `vw` in that test.)  I may have been absent minded.

**Pull request merged**
